name: dry-core
codacy_id: 40946292b9094624beec604a149a6023
gemspec:
  authors: ["Nikita Shilnikov"]
  email: ["fg@flashgordon.ru"]
  summary: "A toolset of small support modules used throughout the dry-rb ecosystem"
  development_dependencies:
    - bundler
    - rake
    - rspec
  runtime_dependencies:
    - [concurrent-ruby, "~> 1.0"]
    - [zeitwerk, "~> 2.6"]
